name: Python package

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  ubuntu:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install pytorch==1.6.0 torchvision==0.7.0 cpuonly -c pytorch
          pip install git+https://github.com/carefree0910/carefree-learn.git@dev
      - name: Test with pytest
        shell: bash -l {0}
        run: |
          pip install pytest
          pip install pytest-cov
          pytest -v --cov